[package]
name = "python"
version = "0.1.0"
edition = "2021"

[lib]
name = "neuromorphic_drivers"
crate-type = ["cdylib"]

[dependencies]
neuromorphic_drivers = {path = "../drivers"}
ndarray = "0.15.6"
pyo3 = {version = "0.18.3", features = ["extension-module"]}
